FROM microsoft/dotnet:2.1-sdk
COPY . /app
WORKDIR /app
#RUN dotnet add package Microsoft.AspNetCore.Mvc.Versioning --version 2.2.0
#RUN dotnet add package Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer --version 2.2.0
#RUN dotnet add package Swashbuckle.AspNetCore --version 2.4.0
#RUN dotnet add package Swashbuckle.AspNetCore.Filters --version 4.5.3
#RUN dotnet add package Microsoft.EntityFrameworkCore.Tools --version 2.1.4
#RUN dotnet add package AutoMapper --version 6.2.2
#RUN dotnet add package System.Linq.Dynamic.Core --version 1.0.8.9
EXPOSE 5001/tcp
RUN chmod 777 ./etc/docker/dotnet/entrypoint.sh
#CMD /bin/bash ./etc/docker/dotnet/entrypoint.sh
CMD ["dotnet", "watch", "run"]